# Generated by Django 6.0.1 on 2026-02-14 20:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='admin_reponse',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='contractor_rating',
            field=models.CharField(choices=[('1', 'Poor'), ('2', 'Good'), ('3', 'Average'), ('4', 'Very Good'), ('5', 'Excellent')], default='3', max_length=30),
        ),
        migrations.AddField(
            model_name='feedback',
            name='feedback_type',
            field=models.CharField(choices=[('complaint', 'Compliant'), ('suggestion', 'Suggestion'), ('question', 'Question'), ('appreciation', 'Appreciation'), ('issue_report', 'Issue Report')], default='compliant', max_length=20),
        ),
        migrations.AddField(
            model_name='feedback',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feedback',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='low', max_length=20),
        ),
        migrations.AddField(
            model_name='feedback',
            name='project_rating',
            field=models.CharField(choices=[('1', 'Poor'), ('2', 'Good'), ('3', 'Average'), ('4', 'Very Good'), ('5', 'Excellent')], default='3', max_length=30),
        ),
        migrations.AddField(
            model_name='feedback',
            name='responded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='submitted', max_length=20),
        ),
        migrations.AddField(
            model_name='feedback',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
