# Generated by Django 6.0.1 on 2026-02-23 13:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feedback_admin_reponse_feedback_contractor_rating_and_more'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='feedback',
            constraint=models.UniqueConstraint(fields=('project', 'user', 'feedback_type', 'message', 'is_anonymous', 'project_rating', 'contractor_rating', 'status'), name='unique_same_feedback_payload'),
        ),
    ]
